<?php
require_once "../../../Wizard.php";

$overwrite = isset($_GET['overwrite']);

if (!$overwrite && $installedVersion != 0){
	header("Location:index.php", false, 303);
	exit;
}

function get_sql(string $name) {
	return file_get_contents("../../../database/Structure/".$name.".sql");
}

$procedures = array(
	"Check_Slug",
);
$tables = array(
	"artworks",
	"categories",
	"tags",

	"art-file",
	"art-tag",

	"pages",
	"settings",
);


$bdd->pdo->setAttribute(PDO::ATTR_EMULATE_PREPARES, false); // Required to work with sql generated by PhpMyAdmin
$bdd->StartTransaction();
try {
	if ($overwrite){
		echo "<h3>Dropping...</h3>";
		$bdd->pdo->exec("SET FOREIGN_KEY_CHECKS = 0");
		foreach($procedures as $item) {
			echo $item."<br/>";
			$bdd->pdo->exec("DROP PROCEDURE IF EXISTS `$item`");
		}
		foreach($tables as $item){
			echo $item."<br/>";
			$bdd->pdo->exec("DROP TABLE IF EXISTS `$item`");
		}
	}

	echo "<h3>Installing procedures...</h3>";
	$bdd->pdo->exec("SET FOREIGN_KEY_CHECKS = 1");
	foreach($procedures as $item){
		echo $item."<br/>";
		$sql = get_sql($item);
		$bdd->pdo->exec($sql);
	}
	echo "<h3>Installing tables...</h3>";
	foreach($tables as $item){
		echo $item."<br/>";
		$sql = get_sql($item);
		$bdd->pdo->exec($sql);
	}

	$bdd->SetSettings(array("dbVersion" => DBService::$version));
} catch (PDOException $e) {
	echo "A database exception occured : <br/>";
	echo $e->getCode()."<br/>";
	echo $e->getMessage()."<br/>";

	if (!$overwrite) {
		?>
		<br/>If the error says the table or procedure already exists in the database, you may try overwriting it.
		<br/><strong>This is a destructive operation; if you are already storing anything in this database, it may become iremediably lost. Please check twice before proceeding.</strong>
		<form method=GET>
			<input type=submit value="Retry"/>
			<br/>
			<input type=checkbox id=overwrite name=overwrite>
			<label for=overwrite>And drop the following tables/procedures : </label>
			<?php
			foreach(array_merge($tables, $procedures) as $item)
				echo "<br/>".$item;
			?>
		</form>
		<?php
	}

	$bdd->Rollback();
	die;
} catch (Exception $e) {
	echo "An unexpected exception occured : <br/>";
	$bdd->Rollback();
	echo $e;
	die;
}
$bdd->CommitTransaction();

echo "<br/><strong>Success !</strong>";
echo "<br/><span title='tanslator's note: keikaku means plan'>All according to keikaku</span>";
echo "<br/>You are free to remove the `databasewizard` folder from the website's structure, you won't need it anymore."
?>